name: CI/CD Pipeline

on: [ push, pull_request, workflow_dispatch ]

env:
  PIP_CACHE_DIR: /tmp/pipcache
  ORIGINAL_REPO: thebjorn/pydeps
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
  REPO: ${{ github.repository }}

jobs:
  lint:
    name: Code linting
    runs-on: ubuntu-latest
    env:
      LINTDIR: ./ghlint

    steps:
      - uses: actions/checkout@v2

      - name: setup directories
        shell: bash
        run: |
          mkdir -p $PIP_CACHE_DIR
          mkdir -p $LINTDIR

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install linters
        run: pip install flake8 pylint

      - name: flake8
        run: flake8 pydeps/** --max-line-length=199

      - name: pylint
        shell: bash
        run: |
          pylint pydeps | tee $LINTDIR/pylint.txt
          exit ${PIPESTATUS[0]}

      ## REPORT ERRORS/LOGS
      - name: Upload logs as artifacts
        if: ${{ failure() }}  # if any step failed
        uses: actions/upload-artifact@v2
        with:
            name: Python ${{ matrix.python-version }} - linter failures
            path: ${{ env.LINTDIR }}/*



  ci:
    name: Continuous Integration
    runs-on: ubuntu-20.04
    container: thebjorn/pydeps-agent:ci-${{ matrix.python-version }}
    outputs:
      package_version: ${{ steps.proj_ver_determiner.outputs.package_version }}
      package_version_tag: ${{ steps.proj_ver_determiner.outputs.package_version_tag }}
      latest_github_tag: ${{ steps.proj_ver_determiner.outputs.latest_github_tag }}
      should_deploy: ${{ steps.proj_ver_determiner.outputs.should_deploy }}
    strategy:
      matrix:
        python-version: [ '2.7', '3.6', '3.7', '3.8', '3.9' ]
    env:
      LOGDIR: ./ghlogs/${{ matrix.python-version }}
    steps:

      - name: Clone repository
        run: |
          git config --global http.sslverify false
          git clone https://github.com/${{ github.repository }}.git .

      - name: Setup directories
        shell: bash
        run: |
          mkdir -p $PIP_CACHE_DIR
          mkdir -p $LOGDIR

      # Information setup

      - name: Get branch name
        shell: bash
        run: echo "CURRENT_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - if: matrix.python-version == '3.9'
        name: Pipeline conditionals handler
        id: conditionals_handler
        shell: bash
        run: |
          GITHUB_REF="${{ github.ref }}"
          GITHUB_EVENT_NAME="${{ github.event_name }}"
          IS_DEFAULT_BRANCH='false'
          IS_PUSH='false'
          IS_PUSH_TO_DEFAULT_BRANCH='false'

          if [ $CURRENT_BRANCH == $DEFAULT_BRANCH ]; then
            IS_DEFAULT_BRANCH='true'
          fi
          if [ $GITHUB_EVENT_NAME == 'push' ]; then
            IS_PUSH='true'
          fi
          if [ $CURRENT_BRANCH == $DEFAULT_BRANCH ] && [ $GITHUB_EVENT_NAME == 'push' ]; then
            IS_PUSH_TO_DEFAULT_BRANCH='true'
          fi

          echo "::set-output name=is_default_branch::$(echo $IS_DEFAULT_BRANCH)"
          echo "::set-output name=is_push::$(echo $IS_PUSH)"
          echo "::set-output name=is_push_to_default_branch::$(echo $IS_PUSH_TO_DEFAULT_BRANCH)"

      - if: steps.conditionals_handler.outputs.is_push_to_default_branch == 'true' && matrix.python-version == '3.9'
        name: Project version/deploy determiner
        id: proj_ver_determiner
        shell: bash
        run: |
          git fetch --all --tags

          PACKAGE_VERSION=$(python3.9 setup.py --version)
          PACKAGE_VERSION_TAG=`echo v$PACKAGE_VERSION | sed -e 's/[[:space:]]//'`
          LATEST_GITHUB_TAG=`echo $(git tag | sort --version-sort | tail -n1)`
          IS_NEW_VERSION=$(python3.9 -c "import sys, packaging.version as v;p=v.parse;s=sys.argv;a=p(s[1]);b=p(s[2]);print((a>b)-(a<b))" $PACKAGE_VERSION_TAG $LATEST_GITHUB_TAG)
          SHOULD_DEPLOY="false"

          if [ -z "$LATEST_GITHUB_TAG" ] || [ $IS_NEW_VERSION == 1 ] && [ "$GITHUB_REPOSITORY" == "$ORIGINAL_REPO" ]; then
            SHOULD_DEPLOY="true"
          fi

          echo "::set-output name=package_version::$(echo $PACKAGE_VERSION)"
          echo "::set-output name=package_version_tag::$(echo $PACKAGE_VERSION_TAG)"
          echo "::set-output name=latest_github_tag::$(echo $LATEST_GITHUB_TAG)"
          echo "::set-output name=should_deploy::$(echo $SHOULD_DEPLOY)"

      ## INSTALL
      # Code validations and logs generation

      - name: Install requirements for Python ${{ matrix.python-version }}
        shell: bash
        run: |
          pip install -r requirements.txt 2>&1 | tee $LOGDIR/requirements.log
          exit ${PIPESTATUS[0]} # without this explicit exit code return, even if the previous command fails, the step won't return error because of 'tee'

      - name: List installed packages
        shell: bash
        run: |
            pip list 2>&1 | tee $LOGDIR/pip-list.log
            exit ${PIPESTATUS[0]}

      ## TEST
      - name: Run tests with pytest
        shell: bash
        run: |
          pytest -vv --cov=pydeps . 2>&1 | tee $LOGDIR/pytest.log
          exit ${PIPESTATUS[0]}

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN}}
          fail_ci_if_error: false

      ## BUILD
      # Package application

      - if: matrix.python-version == '3.9'
        name: Package application
        shell: bash
        run: |
          python3.9 setup.py sdist bdist_wheel

      - if: matrix.python-version == '3.9'
        name: Upload packages as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Packages
          path: dist/


      ## REPORT ERRORS/LOGS
      - name: Upload logs as artifacts
        # if: ${{ failure() }}  # if any step failed
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
            name: Python ${{ matrix.python-version }} - artifacts
            path: ${{ env.LOGDIR }}/*


  cd:
    if: needs.ci.outputs.should_deploy == 'true'
    name: Continuous Deployment
    needs: ci
    runs-on: ubuntu-20.04
    container: thebjorn/pydeps-agent:cd-3.9
    steps:
      - name: Clone repository
        run: |
          git config --global http.sslverify false
          git clone https://token:${{ secrets.GIT_REPO_TOKEN }}@github.com/${{ github.repository }}.git .

      # Download CI artifacts

      - name: Download and extract package artifact
        uses: actions/download-artifact@v2
        with:
          name: Packages
          path: dist/

      # Package deployment

      - name: Package deployment
        shell: bash
        run: |
          twine upload -u __token__ -p ${{ secrets.PYPI_API_TOKEN }} dist/*

      # GitHub deploy

      - name: Create GitHub tag
        uses: actions/github-script@v5
        env:
            RELEASE_TAG: ${{ needs.ci.outputs.package_version_tag }}
        with:
            script: |
                github.rest.git.createRef({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: `refs/tags/${process.env.RELEASE_TAG}`,
                    sha: context.sha
                })

      - name: Create and publish GitHub release
        shell: bash
        run: |
          PACKAGE_VERSION="${{ needs.ci.outputs.package_version }}"
          RELEASE_TAG="${{ needs.ci.outputs.package_version_tag }}"
          PREVIOUS_TAG="${{ needs.ci.outputs.latest_github_tag }}"
          RELEASE_TITLE="Version $PACKAGE_VERSION"
          START_LINE=$(( $( grep -n "## $RELEASE_TAG" CHANGELOG.md | grep -Eo '^[^:]+' ) + 2 ))
          END_LINE=$(( $( grep -n "## $PREVIOUS_TAG" CHANGELOG.md | grep -Eo '^[^:]+' ) - 2 ))
          RELEASE_NOTES=$(echo "$( sed -n "$START_LINE,$END_LINE"p CHANGELOG.md )")
          RELEASE_ASSETS="dist/pydeps-$PACKAGE_VERSION-py3-none-any.whl dist/pydeps-$PACKAGE_VERSION.tar.gz" # list the relative paths to the files separated by a single space

          ls -l dist/*

          gh release create $RELEASE_TAG \
          --title "$RELEASE_TITLE" \
          --notes "$RELEASE_NOTES" \
          $RELEASE_ASSETS
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Built with ❤ by [Pipeline Foundation](https://pipeline.foundation)
